import { useEffect, useRef, useState } from 'react'
import {
  PROJECTION_STEPS,
  CycleTimeStatsTable,
  FpyStatsTable,
  CycleTimeTrendChart,
  CycleTimeHistogramChart,
  FpyTrendChart,
  FailuresParetoChart,
} from '../charts/CycleTimeFpyCharts'
import PartDetailTabs from '../PartDetailTabs'
import { deriveOwnerTeam, getTpgPartDetail, DEMO_RECORDS } from '../../lib/bomguardDemoData'

// Reveals `text` a few characters at a time — the one purely cosmetic touch
// in the whole page, there to sell "an AI just generated this," not to hide
// latency (the text itself is already fully generated by the time this
// mounts).
function TypewriterNarrative({ text }) {
  const [shown, setShown] = useState('')
  const idxRef = useRef(0)

  useEffect(() => {
    idxRef.current = 0
    setShown('')
    const id = setInterval(() => {
      idxRef.current += 3
      setShown(text.slice(0, idxRef.current))
      if (idxRef.current >= text.length) clearInterval(id)
    }, 12)
    return () => clearInterval(id)
  }, [text])

  return <p style={{ whiteSpace: 'pre-wrap' }}>{shown}<span className="typewriter-cursor" /></p>
}

function exportRecordCSV(record) {
  const header = ['Location', 'Part Number', 'Description', 'Status', 'Quantity', 'MO']
  const row = [record.location, record.sn, record.description, record.status, record.quantity, record.mo]
  const csv = [header, row].map(r => r.map(v => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `bom-${record.sn}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

// The consolidated report shown once PipelineRunner finishes all 8 stages —
// spec sheet, MO match result, real chart components fed with the
// deterministic demo analytics, an AI-styled narrative, and the upload
// confirmation (already completed by the pipeline itself).
export default function PipelineReport({ record, analytics, receipt, onReset }) {
  const owner = deriveOwnerTeam(record.sn, record.location)
  const tpgDetail = getTpgPartDetail(record)

  return (
    <div className="mo-result">
      <div className="print-sheet">
        <div className="meta-row">
          <div className="item"><span className="k">Part Number</span><span className="v mono">{record.sn}</span></div>
          <div className="item"><span className="k">Location</span><span className="v mono">{record.location}</span></div>
          <div className="item"><span className="k">Platform</span><span className="v">{record.platform}</span></div>
          <div className="item"><span className="k">Status</span><span className="v">{record.status}</span></div>
          <div className="item"><span className="k">Quantity</span><span className="v mono">{record.quantity}</span></div>
          <div className="item"><span className="k">Release MO</span><span className="v mono">{record.mo}</span></div>
          <div className="item"><span className="k">Designated Owner</span><span className="v">{owner}</span></div>
          <div className="item"><span className="k">Prepared</span><span className="v">{new Date().toLocaleString()}</span></div>
        </div>

        <div className="table-wrap" style={{ marginTop: '1rem' }}>
          <table>
            <thead>
              <tr><th>Location</th><th>Part Number</th><th>Description</th><th>Status</th><th>Qty</th><th>MO</th><th>Result</th></tr>
            </thead>
            <tbody>
              <tr className="row-pass">
                <td>{record.location}</td>
                <td className="mono">{record.sn}</td>
                <td>{record.description}</td>
                <td>{record.status}</td>
                <td className="mono">{record.quantity}</td>
                <td className="mono">{record.mo}</td>
                <td><span className="badge-pass">VERIFIED</span></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="fpy-report" style={{ marginTop: '1.5rem' }}>
          <h3 className="fpy-chart-title">Cycle Time — PT Stage ({analytics.model})</h3>
          <CycleTimeStatsTable stats={analytics.cycleTimePt} />
          <p className="filter-hint" style={{ margin: '.75rem 0 .25rem' }}>Daily trend (median), last {analytics.cycleTimePt.dailyTrend.length} days, with a {PROJECTION_STEPS}-day linear projection</p>
          <CycleTimeTrendChart dailyTrend={analytics.cycleTimePt.dailyTrend} />
          <p className="filter-hint" style={{ margin: '1.25rem 0 .25rem' }}>Duration distribution</p>
          <CycleTimeHistogramChart histogram={analytics.cycleTimePt.histogram} />

          <h3 className="fpy-chart-title" style={{ marginTop: '1.5rem' }}>First Pass Yield</h3>
          <FpyStatsTable fpy={analytics.fpy} />
          <p className="filter-hint" style={{ margin: '.75rem 0 .25rem' }}>Weekly trend, with a {PROJECTION_STEPS}-week linear projection</p>
          <FpyTrendChart fpy={analytics.fpy} />

          <h3 className="fpy-chart-title" style={{ marginTop: '1.5rem' }}>Top Failures — MFG</h3>
          <FailuresParetoChart topFailures={analytics.fpy.MFG.topFailures} envLabel="MFG" />

          <h3 className="fpy-chart-title" style={{ marginTop: '1.5rem' }}>Top Failures — MDAAS</h3>
          <FailuresParetoChart topFailures={analytics.fpy.MDAAS.topFailures} envLabel="MDAAS" />

          <div className="mo-result" style={{ marginTop: '.5rem' }}>
            <h3>AI Prediction</h3>
            <TypewriterNarrative text={analytics.prediction.narrative} />
          </div>
        </div>

        {receipt && (
          <div className="stat-card pass" style={{ maxWidth: 360, marginTop: '1.5rem' }}>
            <div className="val" style={{ fontSize: '1.1rem' }}>Upload Complete</div>
            <div className="lbl">Reference ID</div>
            <div className="stat-card-sub mono">{receipt.referenceId}</div>
            <div className="lbl" style={{ marginTop: '.5rem' }}>Submitted</div>
            <div className="stat-card-sub">{new Date(receipt.submittedAt).toLocaleString()}</div>
          </div>
        )}

        <div className="mo-result" style={{ marginTop: '1.5rem' }}>
          <h3>TPG Info — {tpgDetail.partNumber}</h3>
          <p className="filter-hint" style={{ marginBottom: '.75rem' }}>
            {record.location === 'L11'
              ? 'Live TPG Location detail for this assembly.'
              : `Live TPG Location detail — this part is the blade module referenced in assembly ${DEMO_RECORDS.find(r => r.location === 'L11')?.sn}.`}
          </p>
          <PartDetailTabs partDetail={tpgDetail} />
        </div>
      </div>

      <div className="no-print" style={{ display: 'flex', gap: '.5rem', marginTop: '1.5rem' }}>
        <button type="button" className="export-btn" onClick={() => window.print()}>Print</button>
        <button type="button" className="export-btn" onClick={() => exportRecordCSV(record)}>Export CSV</button>
        <button type="button" className="search-btn" onClick={onReset}>Run Another BOM</button>
      </div>
    </div>
  )
}
